image:
  - Visual Studio 2019

install:
  - choco install gitversion.portable -y

configuration:
  - Release

branches:
  only:
  - master

environment:
  AppVeyorBuild: true
  VersionMajor: '5.2.1'
  
version: '$(VersionMajor).{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '$(VersionMajor)'
  package_version: '$(VersionMajor)'
  assembly_version: '$(VersionMajor)'
  file_version: '{version}'
  informational_version: '{version}'

nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true

before_build:
  - dotnet restore src

build:
  project: src\FlatSharp.sln

after_build:
  - cmd: dotnet pack src\FlatSharp\flatsharp.csproj -c Release -o .\artifacts --include-symbols -v n
  - cmd: dotnet pack src\FlatSharp.Compiler\FlatSharp.Compiler.csproj -c Release -o .\artifacts --include-symbols -v n
  - cmd: dotnet pack src\FlatSharp.Runtime\FlatSharp.Runtime.csproj -c Release -o .\artifacts --include-symbols -v n
  - cmd: dotnet pack src\FlatSharp.Unsafe\FlatSharp.Unsafe.csproj -c Release -o .\artifacts --include-symbols -v n

artifacts:
  - path: '.\artifacts\*.nupkg'
    name: Nuget
